### ISSUE TITLE
Performance in Browser

### ISSUE THREAD

**Issue by chriseth** [wanderer/node-ethereum#16]
This might be a non-issue, but I still wanted to bring it up:
A contract like the following:
```
contract c {
    uint[] data;
    function f() {
        for (uint x = 0; x < 1000 ; x++)
            data[data.length++] = x;
    }
}
```
run inside the browser will stall it (inluding all other tabs) for several minutes. Changing the loop into an infinite loop (and providing 3000000 gas) will make it even worse and crash most of the browsers.
It would be good to know whether this also happens for node.

**Comment by wanderer** [comment]
thanks @chriseth i moved the issue to the correct repo and will look into it
