### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by Gitxx2** [wanderer/node-ethereum#17]
Hi, 
I'm getting the next installing errors (ubuntu, raspberry pi 2). Please help.

npm ERR! fetch failed https://registry.npmjs.org/leveldown/-/leveldown-0.10.6.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 400
npm ERR! fetch failed https://registry.npmjs.org/npmlog/-/npmlog-2.0.3.tgz
npm WARN retry will retry, error on last attempt: Error: getaddrinfo EAI_AGAIN registry.npmjs.org:443
npm ERR! Linux 4.1.19-v7+
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "."
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code EAI_AGAIN
npm ERR! errno EAI_AGAIN
npm ERR! syscall getaddrinfo

npm ERR! getaddrinfo EAI_AGAIN registry.npmjs.org:443
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/node-ethereum/npm-debug.log

**Comment by wanderer** [comment]
This repo has been deprecated; all develpement is now happening here https://github.com/ethereumjs
